### ISSUE TITLE
meta: use issues for defining tasks

### ISSUE THREAD

**Issue by laurentperrinet** [SpikeAI/2020-11_brainhack_Project7#1]
* [x] we will create issues to advance our project
 * [x] please @albertoarturovergani  create one to test the workflow

**Comment by laurentperrinet** [comment]
have you seen I renamed script folder in https://github.com/SpikeAI/2020-11_brainhack_Project7/commit/9cf3e9dd107ec8a2b222efb7ba61aca7064cf136

**Comment by albertoarturovergani** [comment]
I have created the first one for benchmarking, so we could close this #1

**Comment by laurentperrinet** [comment]
Yes I saw https://github.com/SpikeAI/2020-11_brainhack_Project7/issues/2 - let's close this one!

**Comment by laurentperrinet** [comment]
the page on the global brainhack is a good resource= https://github.com/brainhackorg/bhg-event-materials/blob/master/docs/leading_and_attending_to_brainhack_projects.md

**Comment by laurentperrinet** [comment]
BTW, we should have called our repository `2020-12_brainhack_Project7` ...
